### ISSUE TITLE
unlocking wallet with lncli from synology nas

### ISSUE THREAD

**Issue by 3ntranced** [robclark56/RaspiBolt-Extras#1]
Hi Rob, great guides! Any ideas on how to unlock a wallet using lncli running on a synology nas where expect is not available?

**Comment by robclark56** [comment]
I have re-written completely.

Does not use 'expect' at all.

https://github.com/robclark56/RaspiBolt-Extras/blob/master/RB_extra_unlock_PK.md

**Comment by 3ntranced** [comment]
perfect thank you
