### ISSUE TITLE
DHCP reservations or Static IP

### ISSUE THREAD

**Issue by rocky3xr** [robclark56/RaspiBolt-Extras#2]
Hello,

Is it possible tu use DHCP reservations or to configure it It has to be in a Static IP?

**Comment by robclark56** [comment]
I am not clear if you are talking about the LAN IP address or the public IP address?

Here is what I do:

LAN: Have told my firewall router to reserve a local IP address for the RaspiBolt, and set the RaspiBolt to use DHCP. This effectively gives the RasiBolt a static LAN IP address.

WAN: My ISP gives me a dynamic IP. So I use a free dynamic IP service provider (e.g. https://www.makeuseof.com/tag/5-best-dynamic-dns-providers-can-lookup-free-today/) to give my WAN connection a static FQDN.

**Comment by rocky3xr** [comment]
Thanks!
